### ISSUE TITLE
debugging script needed

### ISSUE THREAD

**Issue by HeSe** [GsDevKit/gsApplicationTools#8]
I tried to register a GemServer and start it for debugging purposes via a script based on:
Gemserver instance scriptStartServiceOn:

Unfortunatly the implementation and usage of doTransaction: ends up in a never commited transaction on the server side. Therefore a change in the TestingGemSession won't be recognized in the GemServerDebugging session.

I am not so sure if the current implementation of doTransaction should rather abort an existing transaction on the ZincServer side and always create a new one.....

**Comment by dalehenrich** [comment]
@HeSe I think I've addressed the debugging issue and here' the [relevant documentation](https://github.com/GsDevKit/gsApplicationTools/blob/master/docs/gettingStarted.md#interactive-debugging)
